# Generated by cucumber-sinatra. (2013-02-13 12:53:33 -0500)
ENV['PROJECT_ROOT'] = File.join(File.dirname(__FILE__), '..', '..')
ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/app.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = App::Base

class AppWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  AppWorld.new
end
