language: ruby
rvm:
  #- 1.8.7
  - 1.9.2
  - 1.9.3
  #- jruby-18mode # JRuby in 1.8 mode
  #- jruby-19mode # JRuby in 1.9 mode
  #- rbx-18mode
  #- rbx-19mode

before_script: "sh -e /etc/init.d/xvfb start"

script: "DISPLAY=:99.0  bundle exec rspec spec; bundle exec rake jasmine:headless"
