source 'https://rubygems.org'

gem "sinatra"
gem "sinatra-contrib"
gem "sinatra-session"
gem "sinatra-cross_origin"
gem "rerun"
gem "deep_merge"
gem "mongo"
gem "mongo_ext"
gem "bson", "1.8.5"
gem "bson_ext", "1.8.5"
gem "mongo_mapper"
gem "racksh"
gem "haml"
gem "oats"
gem "thin"
gem "rake"
gem "multi_json"
gem "oj"
gem "liquid"
gem "stasis"
gem "rdiscount", "1.6.8"
gem "net-ping"
gem "net-ldap"
gem "addressable"
gem "hashlib", ">= 0.0.21"
gem "babel_bridge"
gem "eventmachine"
gem "msgpack"
gem "beaneater"
gem "rainbow"
gem "statsd-ruby"
gem "tire"
gem "activerecord", "~> 3"
#gem "activesupport", ">= 3.2"
gem "snmp"

case RUBY_VERSION
when /^1\.8/
  gem "rpam"
else
  gem "rpam-ruby19"
end
