source :rubygems

gem "sinatra"
gem "sinatra-contrib"
gem "sinatra-session"
gem "sinatra-cross_origin"
gem "rb-inotify", "0.8.8"
gem "rerun"
gem "deep_merge"
gem "mongo"
gem "mongo_ext"
gem "bson_ext"
gem "mongo_mapper"
gem "racksh"
gem "haml"
gem "oats"
gem "thin"
gem "rake"
gem "multi_json"
gem "oj"
gem "liquid"
gem "stasis"
gem "rdiscount", "1.6.8"
gem "net-ping"
gem "net-ldap"
gem "addressable"
gem "ruby-pam", :git => "git://github.com/portertech/ruby-pam.git"
#gem "activesupport", ">= 3.2"
gem "hashlib", ">= 0.0.15"
gem "babel_bridge"
gem "eventmachine"
gem "msgpack"
gem "beaneater"
gem "rainbow"

group :test, :development do
#  gem "rack-webconsole"
#  gem "cucumber"
#  gem "cucumber-sinatra"
#  gem "capybara"
#  gem "rspec"
end
