source 'https://rubygems.org'

gem "sinatra"
gem "sinatra-contrib"
gem "sinatra-session"
gem "sinatra-cross_origin"
gem "rerun"
gem "deep_merge"
gem "racksh"
gem "haml"
gem "oats"
gem "thin"
gem "rake"
gem "multi_json"
gem "oj"
gem "liquid"
gem "stasis"
gem "rdiscount", "1.6.8"
gem "net-ping"
gem "net-ldap"
gem "addressable"
gem "hashlib", ">= 0.0.25"
gem "babel_bridge"
gem "eventmachine"
gem "msgpack"
gem "beaneater"
gem "rainbow"
gem "statsd-ruby"
#gem "activerecord", "~> 3"
#gem "activesupport", ">= 3.2"
gem "snmp"
gem "elasticsearch", ">= 0.4.0"
gem "activemodel", ">= 4.0.0"
gem "cucumber"
gem "ipaddress"

case RUBY_VERSION
when /^1\.8/
  gem "rpam"
else
  gem "rpam-ruby19"
end
