development:
  host: localhost
  database: onering_development

test:
  host: localhost
  database: onering_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOLAB_URI'] %>
